name: torch_nas
channels:
  - conda-forge
  - anaconda
  - pyg
  - pytorch
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py310h06a4308_0
  - aiohappyeyeballs=2.4.3=py310h06a4308_0
  - aiohttp=3.10.5=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.3=py310h06a4308_0
  - attrs=24.2.0=py310h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.12.14=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py310h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - grpcio=1.62.2=py310h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - joblib=1.4.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hecde1de_4
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py310h06a4308_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib=3.9.2=py310h06a4308_0
  - matplotlib-base=3.9.2=py310hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.1.0=py310h5eee18b_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py310h5eee18b_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=py310h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - plotly=5.24.1=py310h2f386ee_0
  - ply=3.11=py310h06a4308_0
  - propcache=0.2.0=py310h5eee18b_0
  - psutil=5.9.0=py310h5eee18b_0
  - pyg=2.5.2=py310_torch_2.0.0_cu117
  - pyparsing=3.1.2=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.15=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - safetensors=0.4.4=py310ha89cbab_0
  - scikit-learn=1.5.1=py310h1128e8f_0
  - scipy=1.12.0=py310h5f9d8c6_0
  - setuptools=72.1.0=py310h06a4308_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py310h06a4308_0
  - tensorboard=2.17.0=py310h06a4308_0
  - tensorboard-data-server=0.7.0=py310h52d8a92_1
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - timm=1.0.9=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - torchaudio=2.0.0=py310_cu117
  - torchvision=0.15.0=py310_cu117
  - tornado=6.4.1=py310h5eee18b_0
  - tqdm=4.66.5=py310h2f386ee_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_0
  - urllib3=2.2.3=py310h06a4308_0
  - werkzeug=3.0.6=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py310h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - accelerate==1.7.0
    - adjusttext==1.3.0
    - annotated-types==0.7.0
    - anyio==4.9.0
    - anykeystore==0.2
    - apex==0.1
    - asttokens==3.0.0
    - astunparse==1.6.3
    - cfgv==3.5.0
    - chardet==5.2.0
    - click==8.1.8
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - comm==0.2.2
    - cryptacular==1.6.2
    - custom-quantization-cuda==0.0.0
    - dataproperty==1.1.0
    - datasets==2.0.0
    - debugpy==1.8.14
    - decorator==5.2.1
    - defusedxml==0.7.1
    - dill==0.3.7
    - distlib==0.4.0
    - distro==1.9.0
    - dm-tree==0.1.8
    - dnspython==2.7.0
    - docker-pycreds==0.4.0
    - eagle==1.1.0
    - evaluate==0.4.3
    - exceptiongroup==1.3.0
    - executing==2.2.0
    - flatbuffers==24.3.25
    - fsspec==2023.10.0
    - gast==0.6.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - greenlet==3.1.1
    - h11==0.16.0
    - hf-xet==1.1.2
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.32.2
    - humanfriendly==10.0
    - hupper==1.12.1
    - identify==2.6.15
    - igraph==0.11.8
    - iniconfig==2.1.0
    - ipykernel==6.29.5
    - ipython==8.36.0
    - jedi==0.19.2
    - jiter==0.10.0
    - jsonlines==4.0.0
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kaleido==0.2.1
    - lm-eval==0.3.0
    - lxml==5.4.0
    - markdown-it-py==3.0.0
    - matplotlib-inline==0.1.7
    - mbstrdecoder==1.1.4
    - mdurl==0.1.2
    - multiprocess==0.70.15
    - nas-bench-201==2.1
    - nest-asyncio==1.6.0
    - netron==8.1.7
    - nltk==3.9.1
    - nodeenv==1.9.1
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-dali-cuda110==1.42.0
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvimgcodec-cu11==0.3.0.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - oauthlib==3.2.2
    - onnx==1.17.0
    - onnx-simplifier==0.4.35
    - onnxruntime==1.20.1
    - openai==1.82.0
    - pandas==2.2.1
    - parso==0.8.4
    - pastedeploy==3.1.0
    - pathvalidate==3.2.3
    - pbkdf2==1.3
    - peft==0.15.2
    - pexpect==4.9.0
    - plaster==1.1.2
    - plaster-pastedeploy==1.0.1
    - pluggy==1.6.0
    - portalocker==3.1.1
    - pre-commit==4.2.0
    - progressbar2==4.5.0
    - prompt-toolkit==3.0.51
    - protobuf==5.28.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==20.0.0
    - pyarrow-hotfix==0.7
    - pybind11==2.13.6
    - pycountry==24.6.1
    - pycrawlers==1.1.6
    - pydantic==2.10.5
    - pydantic-core==2.27.2
    - pygments==2.18.0
    - pymongo==4.13.0
    - pyramid==2.0.2
    - pyramid-mailer==0.15.1
    - pytablewriter==1.2.1
    - pytest==8.3.5
    - python-igraph==0.11.8
    - python-utils==3.9.1
    - python3-openid==3.2.0
    - pyzmq==26.4.0
    - regex==2024.11.6
    - repoze-sendmail==4.4.1
    - requests-oauthlib==2.0.0
    - responses==0.18.0
    - rich==13.9.4
    - rouge-score==0.1.2
    - sacrebleu==1.5.0
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - smmap==5.0.2
    - sniffio==1.3.1
    - sqlalchemy==2.0.35
    - sqlitedict==2.1.0
    - stack-data==0.6.3
    - sympy==1.13.1
    - tabledata==1.3.4
    - tabulate==0.9.0
    - tcolorpy==0.1.7
    - tensorrt==10.7.0.post1
    - tensorrt-cu12==10.7.0.post1
    - tensorrt-cu12-bindings==10.7.0.post1
    - tensorrt-cu12-libs==10.7.0.post1
    - texttable==1.7.0
    - thop==0.1.1-2209072238
    - tokenizers==0.21.1
    - torch==2.6.0
    - torch-tensorrt==2.6.0
    - tqdm-multiprocess==0.0.11
    - traitlets==5.14.3
    - transaction==5.0
    - transformers==4.52.3
    - translationstring==1.4
    - triton==3.2.0
    - typepy==1.3.4
    - typing-extensions==4.15.0
    - velruse==1.1.1
    - venusian==3.1.0
    - virtualenv==20.35.4
    - wandb==0.19.2
    - wcwidth==0.2.13
    - webob==1.8.8
    - word2number==1.1
    - wtforms==3.1.2
    - wtforms-recaptcha==0.3.2
    - xxhash==3.5.0
    - zope-deprecation==5.0
    - zope-interface==7.1.0
    - zope-sqlalchemy==3.1
    - zstandard==0.23.0
prefix: /home/ubuntu/software/anaconda3/envs/torch_nas
